//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.06 at 01:37:02 PM MSK 
//


package max_sk.MyWork.soap.tovars;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tovars" type="{http://www.max_sk.com/spring/ws/tovars}tovar" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tovars"
})
@XmlRootElement(name = "getAllTovarsResponse")
public class GetAllTovarsResponse {

    @XmlElement(required = true)
    protected List<Tovar> tovars;

    /**
     * Gets the value of the tovars property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tovars property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTovars().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tovar }
     * 
     * 
     */
    public List<Tovar> getTovars() {
        if (tovars == null) {
            tovars = new ArrayList<Tovar>();
        }
        return this.tovars;
    }

}
